config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get 'all' => 'users#index'
  end

  resources :products

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end

	def show
	end

	def edit
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PREM World</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">P. League</a>
      <div class="nav-collapse">
        <ul class="nav">
          <% if user_signed_in? %> <!--class="glyphicon glyphicon-log-out" -->
            <li><i class="entypo-logout"> </i><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %> </li>
          <% else %>
            <li><i class="entypo-facebook"> </i><%= link_to "Sign in with Email", new_user_session_path%></li>
            <li><i class="entypo-facebook"> </i><%= link_to "Sign Up", new_user_registration_path%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_sent_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :remember_created_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>